pool:
  name: Qest Linux
steps:
  - task: NodeTool@0
    displayName: "Use Node 12.x"
    inputs:
      versionSpec: 12.x

  - task: Npm@1
    displayName: "Use Npm 1.x"

  - script: npm install
    displayName: "npm install"

  - script: npm install react@16.8.4 react-addons-test-utils@15.6.2 immutable babel-polyfill oidc-client
    displayName: "install dependecies"

  - script: "npm run build"
    displayName: "npm run build"

  - task: Npm@1
    displayName: "npm publish"
    inputs:
      command: custom
      verbose: false
      customCommand: "publish --access public"
      customEndpoint: "qest-npm"
