pool:
  name: Qest Linux
steps:
  - task: NodeTool@0
    displayName: "Use Node 12.x"
    inputs:
      versionSpec: 12.x

  - task: geeklearningio.gl-vsts-tasks-yarn.yarn-installer-task.YarnInstaller@3
    displayName: "Use Yarn 1.x"

  - script: npm
    displayName: "npm install"

  - script: "npm run build"
    displayName: "npm run build"

  - task: Npm@1
    displayName: "npm publish"
    inputs:
      command: custom
      verbose: false
      customCommand: "publish --access public"
      customEndpoint: "qest-npm"
